import Head from 'next/head';
import Footer from './Footer';
import Header from './Header';

const Layout = ({ children }: any) => {
  return (
    <>
      <Head>
        <title>NextTS RecipeApp</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main className='min-h-screen max-w-full flex justify-center items-center'>
        {children}
      </main>
      <Footer />
    </>
  );
};

export default Layout;
